version: '3'

#volumes:
#  postgres_data:
#    driver: local

services:
#  postgres:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password

  #  alternative - docker run -e KEYCLOAK_USER=<USERNAME> -e KEYCLOAK_PASSWORD=<PASSWORD> -p 8080:8080 jboss/keycloak
  keycloak-server:
    image: quay.io/keycloak/keycloak:latest

#    build:
#      context: services/keycloak
    volumes:
      - ./keycloak-imports:/opt/jboss/keycloak/imports
#    command:
#      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export-demo.json"

    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export-demo.json
      #DB_VENDOR: POSTGRES
      #DB_ADDR: postgres
      #DB_DATABASE: keycloak
      #DB_USER: keycloak
      #DB_SCHEMA: public
      #DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8180:8080
      - 8181:8443
    #depends_on:
      #- postgres

# Not job 'Could not fetch user details: class org.springframework.security.oauth2.common.exceptions.InvalidRequestException, Possible CSRF detected - state parameter was required but no state could be found'
#  camunda-process:
#    build: ./process-camunda/build/docker
#    environment:
#      KEYCLOAK_URL_AUTH: http://localhost:8180
#      KEYCLOAK_URL_TOKEN: http://localhost:8180
#      KEYCLOAK_URL_PLUGIN: https://keycloak-server:8443
#      KEYCLOAK_CLIENT_ID: camunda-identity-service
#      KEYCLOAK_CLIENT_SECRET: 53ccd25a-379a-464a-9d02-788e28f59489
#    ports:
#    - 8080:8080
#    depends_on:
#      - keycloak-server
#    restart: always

# docker run --network host -p8080:8080  kvsemenov/process-camunda:unspecified